// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: message.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType - тип сообщения.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0 // Тип не задан.
	MessageType_MESSAGE_TYPE_ALERT       MessageType = 1 // Предупреждающее сообщение.
	MessageType_MESSAGE_TYPE_INFO        MessageType = 2 // Информационное сообщение.
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_ALERT",
		2: "MESSAGE_TYPE_INFO",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_ALERT":       1,
		"MESSAGE_TYPE_INFO":        2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Message - сообщение.
type Message struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Type        MessageType            `protobuf:"varint,2,opt,name=type,enum=message.MessageType,def=2"`
	xxx_hidden_Title       *string                `protobuf:"bytes,3,opt,name=title,def=no title"`
	xxx_hidden_Tags        []string               `protobuf:"bytes,4,rep,name=tags"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,5,opt,name=data"`
	xxx_hidden_End         isMessage_End          `protobuf_oneof:"end"`
	xxx_hidden_SentAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=sent_at,json=sentAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

// Default values for Message fields.
const (
	Default_Message_Type  = MessageType_MESSAGE_TYPE_INFO
	Default_Message_Title = string("no title")
)

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Message) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Message) GetType() MessageType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return Default_Message_Type
}

func (x *Message) GetTitle() string {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			if x.xxx_hidden_Title != nil {
				return *x.xxx_hidden_Title
			}
			return Default_Message_Title
		}
	}
	return Default_Message_Title
}

func (x *Message) GetTags() []string {
	if x != nil {
		return x.xxx_hidden_Tags
	}
	return nil
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Message) GetIsLast() bool {
	if x != nil {
		if x, ok := x.xxx_hidden_End.(*message_IsLast); ok {
			return x.IsLast
		}
	}
	return false
}

func (x *Message) GetCountMore() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_End.(*message_CountMore); ok {
			return x.CountMore
		}
	}
	return 0
}

func (x *Message) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_SentAt
	}
	return nil
}

func (x *Message) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *Message) SetType(v MessageType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *Message) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *Message) SetTags(v []string) {
	x.xxx_hidden_Tags = v
}

func (x *Message) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *Message) SetIsLast(v bool) {
	x.xxx_hidden_End = &message_IsLast{v}
}

func (x *Message) SetCountMore(v int32) {
	x.xxx_hidden_End = &message_CountMore{v}
}

func (x *Message) SetSentAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_SentAt = v
}

func (x *Message) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Message) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Message) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Message) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Message) HasEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_End != nil
}

func (x *Message) HasIsLast() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_End.(*message_IsLast)
	return ok
}

func (x *Message) HasCountMore() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_End.(*message_CountMore)
	return ok
}

func (x *Message) HasSentAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SentAt != nil
}

func (x *Message) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *Message) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
}

func (x *Message) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
}

func (x *Message) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Data = nil
}

func (x *Message) ClearEnd() {
	x.xxx_hidden_End = nil
}

func (x *Message) ClearIsLast() {
	if _, ok := x.xxx_hidden_End.(*message_IsLast); ok {
		x.xxx_hidden_End = nil
	}
}

func (x *Message) ClearCountMore() {
	if _, ok := x.xxx_hidden_End.(*message_CountMore); ok {
		x.xxx_hidden_End = nil
	}
}

func (x *Message) ClearSentAt() {
	x.xxx_hidden_SentAt = nil
}

const Message_End_not_set_case case_Message_End = 0
const Message_IsLast_case case_Message_End = 6
const Message_CountMore_case case_Message_End = 7

func (x *Message) WhichEnd() case_Message_End {
	if x == nil {
		return Message_End_not_set_case
	}
	switch x.xxx_hidden_End.(type) {
	case *message_IsLast:
		return Message_IsLast_case
	case *message_CountMore:
		return Message_CountMore_case
	default:
		return Message_End_not_set_case
	}
}

type Message_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// ID сообщения.
	Id *int32
	// Тип сообщения.
	Type *MessageType
	// Заголовок сообщения.
	Title *string
	// Теги сообщения.
	Tags []string
	// Данные сообщения.
	Data []byte
	// Опция конца потока сообщений.

	// Fields of oneof xxx_hidden_End:
	// Флаг последнего сообщения.
	IsLast *bool
	// Количество оставшихся сообщений.
	CountMore *int32
	// -- end of xxx_hidden_End
	// Время отправки сообщения.
	SentAt *timestamppb.Timestamp
}

func (b0 Message_builder) Build() *Message {
	m0 := &Message{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Title = b.Title
	}
	x.xxx_hidden_Tags = b.Tags
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Data = b.Data
	}
	if b.IsLast != nil {
		x.xxx_hidden_End = &message_IsLast{*b.IsLast}
	}
	if b.CountMore != nil {
		x.xxx_hidden_End = &message_CountMore{*b.CountMore}
	}
	x.xxx_hidden_SentAt = b.SentAt
	return m0
}

type case_Message_End protoreflect.FieldNumber

func (x case_Message_End) String() string {
	md := file_message_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isMessage_End interface {
	isMessage_End()
}

type message_IsLast struct {
	// Флаг последнего сообщения.
	IsLast bool `protobuf:"varint,6,opt,name=is_last,json=isLast,oneof"`
}

type message_CountMore struct {
	// Количество оставшихся сообщений.
	CountMore int32 `protobuf:"varint,7,opt,name=count_more,json=countMore,oneof"`
}

func (*message_IsLast) isMessage_End() {}

func (*message_CountMore) isMessage_End() {}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12;\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.message.MessageType:\x11MESSAGE_TYPE_INFOR\x04type\x12\x1e\n" +
	"\x05title\x18\x03 \x01(\t:\bno titleR\x05title\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x19\n" +
	"\ais_last\x18\x06 \x01(\bH\x00R\x06isLast\x12\x1f\n" +
	"\n" +
	"count_more\x18\a \x01(\x05H\x00R\tcountMore\x123\n" +
	"\asent_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAtB\x05\n" +
	"\x03end*Z\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MESSAGE_TYPE_ALERT\x10\x01\x12\x15\n" +
	"\x11MESSAGE_TYPE_INFO\x10\x02B\vZ\t./serviceb\beditionsp\xe9\a"

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_proto_goTypes = []any{
	(MessageType)(0),              // 0: message.MessageType
	(*Message)(nil),               // 1: message.Message
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_message_proto_depIdxs = []int32{
	0, // 0: message.Message.type:type_name -> message.MessageType
	2, // 1: message.Message.sent_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[0].OneofWrappers = []any{
		(*message_IsLast)(nil),
		(*message_CountMore)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
