// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_ProcessMessage_FullMethodName                    = "/service.Service/ProcessMessage"
	Service_ProcessMessageRequestStream_FullMethodName       = "/service.Service/ProcessMessageRequestStream"
	Service_ProcessMessageResponseStream_FullMethodName      = "/service.Service/ProcessMessageResponseStream"
	Service_ProcessMessageBidirectionalStream_FullMethodName = "/service.Service/ProcessMessageBidirectionalStream"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service - сервис обработки сообщений.
type ServiceClient interface {
	// ProcessMessage получает сообщение, возвращает сообщение.
	ProcessMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	// ProcessMessageRequestStream получает поток сообщений, возвращает список сообщений.
	ProcessMessageRequestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Message, Messages], error)
	// ProcessMessageResponseStream получает список сообщений, возвращает поток сообщений.
	ProcessMessageResponseStream(ctx context.Context, in *Messages, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error)
	// ProcessMessageBidirectionalStream получает поток сообщений, возвращает поток сообщений.
	ProcessMessageBidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) ProcessMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, Service_ProcessMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ProcessMessageRequestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Message, Messages], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[0], Service_ProcessMessageRequestStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Messages]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Service_ProcessMessageRequestStreamClient = grpc.ClientStreamingClient[Message, Messages]

func (c *serviceClient) ProcessMessageResponseStream(ctx context.Context, in *Messages, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[1], Service_ProcessMessageResponseStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Messages, Message]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Service_ProcessMessageResponseStreamClient = grpc.ServerStreamingClient[Message]

func (c *serviceClient) ProcessMessageBidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[2], Service_ProcessMessageBidirectionalStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Service_ProcessMessageBidirectionalStreamClient = grpc.BidiStreamingClient[Message, Message]

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility.
//
// Service - сервис обработки сообщений.
type ServiceServer interface {
	// ProcessMessage получает сообщение, возвращает сообщение.
	ProcessMessage(context.Context, *Message) (*Message, error)
	// ProcessMessageRequestStream получает поток сообщений, возвращает список сообщений.
	ProcessMessageRequestStream(grpc.ClientStreamingServer[Message, Messages]) error
	// ProcessMessageResponseStream получает список сообщений, возвращает поток сообщений.
	ProcessMessageResponseStream(*Messages, grpc.ServerStreamingServer[Message]) error
	// ProcessMessageBidirectionalStream получает поток сообщений, возвращает поток сообщений.
	ProcessMessageBidirectionalStream(grpc.BidiStreamingServer[Message, Message]) error
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) ProcessMessage(context.Context, *Message) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessMessage not implemented")
}
func (UnimplementedServiceServer) ProcessMessageRequestStream(grpc.ClientStreamingServer[Message, Messages]) error {
	return status.Error(codes.Unimplemented, "method ProcessMessageRequestStream not implemented")
}
func (UnimplementedServiceServer) ProcessMessageResponseStream(*Messages, grpc.ServerStreamingServer[Message]) error {
	return status.Error(codes.Unimplemented, "method ProcessMessageResponseStream not implemented")
}
func (UnimplementedServiceServer) ProcessMessageBidirectionalStream(grpc.BidiStreamingServer[Message, Message]) error {
	return status.Error(codes.Unimplemented, "method ProcessMessageBidirectionalStream not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}
func (UnimplementedServiceServer) testEmbeddedByValue()                 {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_ProcessMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ProcessMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_ProcessMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ProcessMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ProcessMessageRequestStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceServer).ProcessMessageRequestStream(&grpc.GenericServerStream[Message, Messages]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Service_ProcessMessageRequestStreamServer = grpc.ClientStreamingServer[Message, Messages]

func _Service_ProcessMessageResponseStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Messages)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).ProcessMessageResponseStream(m, &grpc.GenericServerStream[Messages, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Service_ProcessMessageResponseStreamServer = grpc.ServerStreamingServer[Message]

func _Service_ProcessMessageBidirectionalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceServer).ProcessMessageBidirectionalStream(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Service_ProcessMessageBidirectionalStreamServer = grpc.BidiStreamingServer[Message, Message]

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMessage",
			Handler:    _Service_ProcessMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessMessageRequestStream",
			Handler:       _Service_ProcessMessageRequestStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ProcessMessageResponseStream",
			Handler:       _Service_ProcessMessageResponseStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ProcessMessageBidirectionalStream",
			Handler:       _Service_ProcessMessageBidirectionalStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
