// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\aservice\x1a\rmessage.proto2\x99\x02\n" +
	"\aService\x124\n" +
	"\x0eProcessMessage\x12\x10.message.Message\x1a\x10.message.Message\x12D\n" +
	"\x1bProcessMessageRequestStream\x12\x10.message.Message\x1a\x11.message.Messages(\x01\x12E\n" +
	"\x1cProcessMessageResponseStream\x12\x11.message.Messages\x1a\x10.message.Message0\x01\x12K\n" +
	"!ProcessMessageBidirectionalStream\x12\x10.message.Message\x1a\x10.message.Message(\x010\x01B\vZ\t./serviceb\beditionsp\xe9\a"

var file_service_proto_goTypes = []any{
	(*Message)(nil),  // 0: message.Message
	(*Messages)(nil), // 1: message.Messages
}
var file_service_proto_depIdxs = []int32{
	0, // 0: service.Service.ProcessMessage:input_type -> message.Message
	0, // 1: service.Service.ProcessMessageRequestStream:input_type -> message.Message
	1, // 2: service.Service.ProcessMessageResponseStream:input_type -> message.Messages
	0, // 3: service.Service.ProcessMessageBidirectionalStream:input_type -> message.Message
	0, // 4: service.Service.ProcessMessage:output_type -> message.Message
	1, // 5: service.Service.ProcessMessageRequestStream:output_type -> message.Messages
	0, // 6: service.Service.ProcessMessageResponseStream:output_type -> message.Message
	0, // 7: service.Service.ProcessMessageBidirectionalStream:output_type -> message.Message
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
