edition = "2024";

package service;

import "message.proto";

option go_package = "./service";

// Service - сервис обработки сообщений.
service Service {
  // ProcessMessage получает сообщение, возвращает сообщение.
  rpc ProcessMessage(message.Message) returns (message.Message);
  // ProcessMessageRequestStream получает поток сообщений, возвращает список сообщений.
  rpc ProcessMessageRequestStream(stream message.Message) returns (message.Messages);
  // ProcessMessageResponseStream получает список сообщений, возвращает поток сообщений.
  rpc ProcessMessageResponseStream(message.Messages) returns (stream message.Message);
  // ProcessMessageBidirectionalStream получает поток сообщений, возвращает поток сообщений.
  rpc ProcessMessageBidirectionalStream(stream message.Message) returns (stream message.Message);
}